package com.simplee2eechat.app

import android.app.Activity
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.*
import android.text.*
import android.view.*
import android.widget.*
import java.util.concurrent.Executors

class ChatActivity:Activity(){
 private val exec=Executors.newSingleThreadExecutor();private val main=Handler(Looper.getMainLooper());private lateinit var store:SecureStore;private var api:ApiClient?=null;private var myId="";private var myName="";private var myUsername="";private var peer="";private var peerName="";private var polling=false;private var incomingPolling=true
 private val primary=0xFF2563EB.toInt();private val bg=0xFFF7F9FC.toInt();private val text=0xFF172033.toInt()
 private fun dp(x:Int)=(x*resources.displayMetrics.density).toInt();private fun tv(s:String,size:Float=16f,bold:Boolean=false)=TextView(this).apply{text=s;textSize=size;setTextColor(text);if(bold)typeface=Typeface.DEFAULT_BOLD};private fun ed(h:String)=EditText(this).apply{hint=h;isSingleLine=true;textSize=16f;setPadding(dp(16),0,dp(16),0);background=round(Color.WHITE,14,0xFFD9E0EA.toInt())};private fun btn(s:String,p:Boolean=false)=Button(this).apply{text=s;isAllCaps=false;setTextColor(if(p)Color.WHITE else text);background=round(if(p)primary else Color.WHITE,14,if(p)primary else 0xFFD9E0EA.toInt());stateListAnimator=null;minHeight=dp(48)};private fun round(c:Int,r:Int,st:Int=0)=GradientDrawable().apply{setColor(c);cornerRadius=dp(r).toFloat();if(st!=0)setStroke(dp(1),st)};private fun root()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(20),dp(18),dp(20),dp(16))}
 override fun onCreate(b:Bundle?){super.onCreate(b);store=SecureStore(this);val id=store.userId();val pw=store.password();if(!id.isNullOrBlank()&&!pw.isNullOrBlank()&&!store.privateKeyBlob().isNullOrBlank())login(id,pw)else showLogin()}
 private fun server()="https://simple-e2ee-chat.onrender.com"
 private fun login(id:String,pw:String){exec.execute{try{val r=ApiClient.login(server(),id,pw);store.saveAccount(r.id,r.token,store.privateKeyBlob()!!,r.publicKey,r.displayName,pw);myId=r.id;myName=r.displayName;api=ApiClient(server(),r.token);main.post{showChats()}}catch(_:Exception){main.post{showLogin()}}}}
 private fun showLogin(){val r=root();r.gravity=Gravity.CENTER_HORIZONTAL;r.addView(tv("Simple E2EE Chat",30f,true));r.addView(tv("Private messaging without a phone number",16f).apply{setPadding(0,dp(8),0,dp(28))});val id=ed("Messenger ID or username");val pw=ed("Password");pw.inputType=129;r.addView(id,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(12)});r.addView(pw,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(14)});val status=tv("",14f);r.addView(status);val b=btn("Log in",true);r.addView(b,LinearLayout.LayoutParams(-1,dp(52)).apply{topMargin=dp(8)});val c=btn("Create a new account");r.addView(c,LinearLayout.LayoutParams(-1,dp(50)).apply{topMargin=dp(10)});setContentView(r);b.setOnClickListener{if(id.text.isBlank()||pw.text.length<8){status.text="Enter your ID and password";return@setOnClickListener};b.isEnabled=false;status.text="Signing in…";login(id.text.toString().trim(),pw.text.toString())};c.setOnClickListener{showSignup()}}
 private fun showSignup(){val r=root();r.addView(tv("Create your account",28f,true));r.addView(tv("Choose an ID that friends can search for.",15f).apply{setPadding(0,dp(8),0,dp(22))});val u=ed("Your ID  •  e.g. rahul_123");val n=ed("Your name");val p=ed("Password  •  8+ characters");p.inputType=129;r.addView(u,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(10)});r.addView(n,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(10)});r.addView(p,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(12)});val s=tv("",13f);r.addView(s);val b=btn("Create account",true);r.addView(b,LinearLayout.LayoutParams(-1,dp(52)).apply{topMargin=dp(10)});setContentView(r);b.setOnClickListener{val us=u.text.toString().trim();if(!us.matches(Regex("[A-Za-z][A-Za-z0-9_]{2,19}"))||n.text.isBlank()||p.text.length<8){s.text="Use a valid ID, name and 8+ character password";return@setOnClickListener};b.isEnabled=false;s.text="Creating secure identity…";exec.execute{try{val k=Crypto.generateKeyPair();val a=ApiClient.register(server(),us,n.text.toString().trim(),p.text.toString(),k.publicKey);store.saveAccount(a.id,a.token,k.privateKey,a.publicKey,n.text.toString().trim(),p.text.toString());myId=a.id;myName=n.text.toString().trim();api=ApiClient(server(),a.token);main.post{showChats()}}catch(e:Exception){main.post{b.isEnabled=true;s.text=e.message?:"Could not create account"}}}}}
 private fun showChats(){polling=false;val r=root();r.setPadding(0,0,0,0);val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(18),dp(18),dp(12),dp(14));setBackgroundColor(Color.WHITE)};val title=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};title.addView(tv("Chats",28f,true));title.addView(tv(myName,13f));h.addView(title,LinearLayout.LayoutParams(0,-2,1f));r.addView(h);val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),dp(12),dp(12),dp(12))};r.addView(ScrollView(this).apply{addView(list)},LinearLayout.LayoutParams(-1,0,1f));list.addView(tv("Start a new private chat",20f,true).apply{gravity=Gravity.CENTER;setPadding(0,dp(70),0,dp(10))});list.addView(tv("Your messages are encrypted before they leave this phone.",14f).apply{gravity=Gravity.CENTER});val b=btn("＋ New chat",true);r.addView(b,LinearLayout.LayoutParams(-1,dp(52)).apply{setMargins(dp(12),dp(8),dp(12),dp(12)});setContentView(r);b.setOnClickListener{showSearch()};pollIncoming()}
 private fun showSearch(){val r=root();val back=btn("‹");r.addView(back,LinearLayout.LayoutParams(dp(52),dp(48)));r.addView(tv("New chat",23f,true));val q=ed("Search by name or ID…");r.addView(q,LinearLayout.LayoutParams(-1,dp(56)).apply{topMargin=dp(14)});val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};r.addView(box,LinearLayout.LayoutParams(-1,0,1f));val status=tv("Type to search",13f);r.addView(status);setContentView(r);back.setOnClickListener{showChats()};q.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){search(s?.toString().orEmpty(),box,status)};override fun afterTextChanged(e:Editable?){} })}
 private fun search(q:String,box:LinearLayout,status:TextView){box.removeAllViews();if(q.isBlank()){status.text="Type to search";return};status.text="Searching…";exec.execute{try{val us=api?.let{client->client.getUser(q)}?.let{listOf(it)}?:emptyList();main.post{box.removeAllViews();if(us.isEmpty()){status.text="No user found";return@post};status.text="Select a user";us.forEach{u->val row=btn("${u.displayName}\n@${u.username}");box.addView(row);row.setOnClickListener{peer=u.id;peerName=u.displayName;showChat()}}}}catch(_:Exception){main.post{status.text="No exact ID found. Enter the E2E-XXXXXXXX Messenger ID."}}}}
 private fun showChat(){polling=true;val r=root();r.setPadding(0,0,0,0);val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(8),dp(8),dp(8),dp(8));setBackgroundColor(Color.WHITE)};val back=btn("‹");h.addView(back,LinearLayout.LayoutParams(dp(50),dp(48)));h.addView(tv(peerName,18f,true),LinearLayout.LayoutParams(0,-2,1f));val voice=btn("☎");val video=btn("▣");h.addView(voice,LinearLayout.LayoutParams(dp(52),dp(48)));h.addView(video,LinearLayout.LayoutParams(dp(52),dp(48)));r.addView(h);val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),dp(12),dp(12),dp(8))};val scroll=ScrollView(this).apply{addView(box)};r.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));val compose=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(dp(10),dp(8),dp(10),dp(12));setBackgroundColor(Color.WHITE)};val input=ed("Message");val send=btn("Send",true);compose.addView(input,LinearLayout.LayoutParams(0,dp(52),1f).apply{rightMargin=dp(8)});compose.addView(send,LinearLayout.LayoutParams(dp(82),dp(52)));r.addView(compose);setContentView(r);back.setOnClickListener{polling=false;showChats()};voice.setOnClickListener{startCall("voice")};video.setOnClickListener{startCall("video")};send.setOnClickListener{val body=input.text.toString().trim();if(body.isBlank())return@setOnClickListener;send.isEnabled=false;exec.execute{try{val c=api?:error("login required");val u=c.getUser(peer);val env=Crypto.encrypt(body,u.publicKey,store.publicKey()?:error("public key missing"));c.sendMessage(peer,myId,env);main.post{input.setText("");send.isEnabled=true;load(box,scroll)}}catch(e:Exception){main.post{send.isEnabled=true;Toast.makeText(this,e.message?:"Message delivery failed",Toast.LENGTH_LONG).show()}}}};load(box,scroll)}
 private fun load(box:LinearLayout,scroll:ScrollView){if(!polling)return;exec.execute{try{val ms=api?.conversation(peer).orEmpty();main.post{box.removeAllViews();ms.forEach{m->val mine=m.from==myId;val body=try{Crypto.decrypt(m.envelope,store.privateKeyBlob()!!,mine)}catch(e:Exception){"[Encrypted message unavailable]"};val b=tv(body,16f);b.setPadding(dp(14),dp(10),dp(14),dp(10));b.background=round(if(mine)primary else Color.WHITE,18);val row=LinearLayout(this).apply{gravity=if(mine)Gravity.END else Gravity.START};row.addView(b);box.addView(row,LinearLayout.LayoutParams(-1,-2).apply{bottomMargin=dp(7)})};scroll.post{scroll.fullScroll(View.FOCUS_DOWN)}}}catch(e:Exception){};main.postDelayed({load(box,scroll)},2500)}}
 private fun startCall(type:String){exec.execute{try{val i=Intent(this,CallActivity::class.java).putExtra("peer",peer).putExtra("type",type).putExtra("caller",true);main.post{startActivity(i)}}catch(e:Exception){main.post{Toast.makeText(this,e.message?:"Unable to start call",Toast.LENGTH_LONG).show()}}}}
 private fun pollIncoming(){if(!incomingPolling)return;exec.execute{try{val calls=api?.incoming(myId).orEmpty();val c=calls.firstOrNull();if(c!=null){main.post{val i=Intent(this,CallActivity::class.java).putExtra("callId",c.id).putExtra("type",c.type).putExtra("caller",false).putExtra("peer",c.caller);startActivity(i)}}}catch(_:Exception){};main.postDelayed({pollIncoming()},2500)}}
 override fun onDestroy(){polling=false;incomingPolling=false;exec.shutdownNow();super.onDestroy()}
}
