package com.simplee2eechat.app

import android.app.Activity
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.*
import android.text.*
import android.view.*
import android.widget.*
import java.util.concurrent.Executors

class ChatActivity : Activity() {
 private val executor=Executors.newSingleThreadExecutor(); private val main=Handler(Looper.getMainLooper())
 private lateinit var store:SecureStore; private var api:ApiClient?=null; private var myId=""; private var myName=""; private var myUsername=""; private var peer=""; private var peerName=""; private var polling=false
 private val bg=0xFFF7F9FC.toInt(); private val textColor=0xFF172033.toInt(); private val primary=0xFF2563EB.toInt()
 private fun dp(x:Int)= (x*resources.displayMetrics.density).toInt()
 private fun tv(s:String,size:Float=16f,bold:Boolean=false)=TextView(this).apply{ text=s;textSize=size;setTextColor(textColor);if(bold)typeface=Typeface.DEFAULT_BOLD }
 private fun ed(h:String)=EditText(this).apply{hint=h;isSingleLine=true;textSize=16f;setPadding(dp(16),0,dp(16),0);background=round(Color.WHITE,14,0xFFD9E0EA.toInt())}
 private fun btn(s:String,primaryBtn:Boolean=false)=Button(this).apply{text=s;isAllCaps=false;setTextColor(if(primaryBtn)Color.WHITE else textColor);background=round(if(primaryBtn)primary else Color.WHITE,14,if(primaryBtn)primary else 0xFFD9E0EA.toInt());stateListAnimator=null;minHeight=dp(48)}
 private fun round(fill:Int,r:Int,stroke:Int=0)=GradientDrawable().apply{setColor(fill);cornerRadius=dp(r).toFloat();if(stroke!=0)setStroke(dp(1),stroke)}
 private fun root()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(20),dp(18),dp(20),dp(16))}
 override fun onCreate(b:Bundle?){super.onCreate(b);store=SecureStore(this);val id=store.userId();val pw=store.password();if(!id.isNullOrBlank()&&!pw.isNullOrBlank()&&!store.privateKeyBlob().isNullOrBlank())login(id,pw)else showLogin()}
 private fun login(id:String,pw:String){executor.execute{try{val r=ApiClient.login(server(),id,pw);store.saveAccount(r.id,r.token,store.privateKeyBlob()!!,r.publicKey,r.displayName,pw);myId=r.id;myName=r.displayName;myUsername=r.username;getPreferences(0).edit().putString("username",myUsername).apply();api=ApiClient(server(),r.token);main.post{showChats()}}catch(e:Exception){main.post{showLogin()}}}}
 private fun showLogin(){val r=root();r.gravity=Gravity.CENTER_HORIZONTAL;r.addView(tv("Simple E2EE Chat",30f,true));r.addView(tv("Private messaging without a phone number",16f).apply{setPadding(0,dp(8),0,dp(28))});val id=ed("Your ID or username");val pw=ed("Password");pw.inputType=129;r.addView(id,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(12)});r.addView(pw,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(14)});val status=tv("",14f);r.addView(status);val b=btn("Log in",true);r.addView(b,LinearLayout.LayoutParams(-1,dp(52)).apply{topMargin=dp(8)});val c=btn("Create a new account");r.addView(c,LinearLayout.LayoutParams(-1,dp(50)).apply{topMargin=dp(10)});r.addView(tv("Use your chosen ID to log in on this device.",12f));setContentView(r);b.setOnClickListener{if(id.text.toString().trim().isBlank()||pw.text.length<8){status.text="Enter your ID and password";return@setOnClickListener};b.isEnabled=false;status.text="Signing in…";login(id.text.toString().trim(),pw.text.toString())};c.setOnClickListener{showSignup()}}
 private fun showSignup(){val r=root();r.addView(tv("Create your account",28f,true));r.addView(tv("Choose an ID that friends can search for.",15f).apply{setPadding(0,dp(8),0,dp(22))});val username=ed("Your ID  •  e.g. rahul_123");val name=ed("Your name");val pw=ed("Password  •  8+ characters");pw.inputType=129;r.addView(username,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(10)});r.addView(name,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(10)});r.addView(pw,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(12)});val status=tv("IDs: 3–20 characters, starting with a letter.",13f);r.addView(status);val create=btn("Create account",true);r.addView(create,LinearLayout.LayoutParams(-1,dp(52)).apply{topMargin=dp(10)});val back=btn("Back to login");r.addView(back,LinearLayout.LayoutParams(-1,dp(50)).apply{topMargin=dp(8)});setContentView(r);create.setOnClickListener{val u=username.text.toString().trim();val n=name.text.toString().trim();val p=pw.text.toString();if(!u.matches(Regex("[A-Za-z][A-Za-z0-9_]{2,19}"))||n.isBlank()||p.length<8){status.text="Please enter a valid ID, name and 8+ character password";return@setOnClickListener};create.isEnabled=false;status.text="Creating secure identity…";executor.execute{try{val k=Crypto.generateKeyPair();val a=ApiClient.register(server(),u,n,p,k.publicKey);store.saveAccount(a.id,a.token,k.privateKey,a.publicKey,n,p);getPreferences(0).edit().putString("username",u).apply();myId=a.id;myUsername=u;myName=n;api=ApiClient(server(),a.token);main.post{showChats()}}catch(e:Exception){main.post{create.isEnabled=true;status.text=e.message?:"Could not create account"}}}};back.setOnClickListener{showLogin()}}
 private fun server()="https://simple-e2ee-chat.onrender.com"
 private fun showChats(){polling=false;val r=root();r.setPadding(0,0,0,0);val head=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(18),dp(18),dp(12),dp(14));setBackgroundColor(Color.WHITE)};val t=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};t.addView(tv("Chats",28f,true));t.addView(tv(if(myUsername.isBlank())myName else "@$myUsername",13f));head.addView(t,LinearLayout.LayoutParams(0,-2,1f));val me=btn("My ID");head.addView(me,LinearLayout.LayoutParams(dp(76),dp(44)));r.addView(head);val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),dp(12),dp(12),dp(12))};val scroll=ScrollView(this).apply{addView(list)};r.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));list.addView(tv("No chats yet",20f,true).apply{gravity=Gravity.CENTER;setPadding(0,dp(60),0,dp(10))});list.addView(tv("Tap New chat and type at least one letter.",14f).apply{gravity=Gravity.CENTER});val bottom=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(dp(12),dp(8),dp(12),dp(12));setBackgroundColor(Color.WHITE)};val n=btn("＋ New chat",true);bottom.addView(n,LinearLayout.LayoutParams(0,dp(52),1f));r.addView(bottom);setContentView(r);n.setOnClickListener{showSearch()};me.setOnClickListener{Toast.makeText(this,"Your ID: ${if(myUsername.isBlank())myId else "@$myUsername"}",Toast.LENGTH_LONG).show()}}
 private fun showSearch(){val r=root();r.setPadding(dp(16),dp(12),dp(16),dp(16));val top=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};val back=btn("‹");top.addView(back,LinearLayout.LayoutParams(dp(52),dp(48)));top.addView(tv("New chat",23f,true).apply{setPadding(dp(10),0,0,0)});r.addView(top);r.addView(tv("Search by ID or name",15f).apply{setPadding(dp(4),dp(12),0,dp(8))});val q=ed("Start typing a name or ID…");r.addView(q,LinearLayout.LayoutParams(-1,dp(56)));val results=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};r.addView(results,LinearLayout.LayoutParams(-1,0,1f));val status=tv("Type one or more letters to see matching users.",13f);r.addView(status);setContentView(r);back.setOnClickListener{showChats()};q.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,st:Int,c:Int,a:Int){};override fun onTextChanged(s:CharSequence?,st:Int,b:Int,c:Int){searchUsers(s?.toString().orEmpty(),results,status)};override fun afterTextChanged(e:Editable?){} })}
 private fun searchUsers(q:String,box:LinearLayout,status:TextView){box.removeAllViews();if(q.isBlank()){status.text="Type one or more letters to see matching users.";return};status.text="Searching…";executor.execute{try{val users=api?.searchUsers(q).orEmpty();main.post{box.removeAllViews();if(users.isEmpty()){status.text="No match found";return@post};status.text="Select a user";users.forEach{u->val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(10),dp(9),dp(10),dp(9));background=round(Color.WHITE,14,0xFFE0E5EC.toInt())};val a=TextView(this).apply{text=u.displayName.take(1).uppercase();textSize=19f;gravity=Gravity.CENTER;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD;background=round(primary,50)};row.addView(a,LinearLayout.LayoutParams(dp(46),dp(46)).apply{rightMargin=dp(12)});val info=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};info.addView(tv(u.displayName,16f,true));info.addView(tv("@${u.username}",13f));row.addView(info,LinearLayout.LayoutParams(0,-2,1f));row.setOnClickListener{peer=u.id;peerName=u.displayName;showChat()};box.addView(row,LinearLayout.LayoutParams(-1,dp(66)).apply{bottomMargin=dp(7)})}}}catch(e:Exception){main.post{status.text=e.message?:"Search failed"}}}}
 private fun showChat(){polling=true;val r=root();r.setPadding(0,0,0,0);val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(8),dp(8),dp(12),dp(8));setBackgroundColor(Color.WHITE)};val back=btn("‹");h.addView(back,LinearLayout.LayoutParams(dp(50),dp(48)));h.addView(tv(peerName,18f,true).apply{setPadding(dp(10),0,0,0)},LinearLayout.LayoutParams(0,-2,1f));r.addView(h);val msgs=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),dp(12),dp(12),dp(8))};val scroll=ScrollView(this).apply{addView(msgs)};r.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));val compose=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(dp(10),dp(8),dp(10),dp(12));setBackgroundColor(Color.WHITE)};val input=ed("Message");val send=btn("Send",true);compose.addView(input,LinearLayout.LayoutParams(0,dp(52),1f).apply{rightMargin=dp(8)});compose.addView(send,LinearLayout.LayoutParams(dp(82),dp(52)));r.addView(compose);setContentView(r);back.setOnClickListener{polling=false;showChats()};send.setOnClickListener{val body=input.text.toString().trim();if(body.isBlank())return@setOnClickListener;send.isEnabled=false;executor.execute{try{val c=api?:error("login required");val u=c.getUser(peer);val env=Crypto.encrypt(body,u.publicKey);c.sendMessage(peer,myId,env);main.post{input.setText("");send.isEnabled=true}}catch(e:Exception){main.post{send.isEnabled=true;Toast.makeText(this,e.message?:"Send failed",Toast.LENGTH_SHORT).show()}}}};pollMessages(msgs,scroll)}
 private fun pollMessages(box:LinearLayout,scroll:ScrollView){if(!polling)return;executor.execute{try{val ms=api?.conversation(peer).orEmpty();val mine=myId;main.post{box.removeAllViews();ms.forEach{m->val body=if(m.from==mine)"[sent]"else try{Crypto.decrypt(m.envelope,store.privateKeyBlob()!!)}catch(_:Exception){"[unable to decrypt]"};val b=tv(body,16f);b.setPadding(dp(14),dp(10),dp(14),dp(10));b.background=round(if(m.from==mine)primary else Color.WHITE,18);val row=LinearLayout(this).apply{gravity=if(m.from==mine)Gravity.END else Gravity.START};row.addView(b);box.addView(row,LinearLayout.LayoutParams(-1,-2).apply{bottomMargin=dp(7)})};scroll.post{scroll.fullScroll(View.FOCUS_DOWN)}}}catch(_:Exception){};main.postDelayed({pollMessages(box,scroll)},3000)}}
 override fun onDestroy(){polling=false;executor.shutdownNow();super.onDestroy()}
}
