services:
  - type: web
    name: simple-e2ee-chat-api-sajju8378
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 22
